name: build

on:
  push

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install buf command
        uses: bufbuild/buf-setup-action@v1

      - uses: bufbuild/buf-lint-action@v1

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install buf command
        uses: bufbuild/buf-setup-action@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install Protoc gen plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest

      - name: Build
        run: make

      - name: Detect Changed files
        uses: tj-actions/verify-changed-files@v11.1
        id: verify-changed-files
        with:
          files: |
            **/*.go
            **/*.md

      - name: Verify Changed files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Go stubs or doc need to be refreshed !')