name: build

on:
  push

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - name: Install buf command
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-lint-action@v1

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - name: Install buf command
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ github.token }}

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ~1.22

      - name: Build
        run: |
          make prepare
          make

      - name: Detect Changed files
        uses: tj-actions/changed-files@v45
        id: verify-changed-files
        with:
          files: |
            **/*.go
            **/*.md

      - name: Verify Changed files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            core.setFailed('Go stubs or doc need to be refreshed !')