name: build

on:
  push

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install buf command
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-lint-action@v1

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install buf command
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ github.token }}

      - name: Build
        run: make

      - name: Detect Changed files
        uses: tj-actions/changed-files@v44
        id: verify-changed-files
        with:
          files: |
            **/*.go
            **/*.md

      - name: Verify Changed files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Go stubs or doc need to be refreshed !')