name: build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1

      - uses: bufbuild/buf-lint-action@v1

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'contracts'
          against: 'https://github.com/michaelcoll/gallery-proto.git#branch=main,ref=HEAD~1,subdir=contracts'